#!/usr/bin/with-contenv bash

# create our folders
mkdir -p  \
	/config/.airdc++

# copy config file
[[ ! -e /config/.airdc++/WebServer.xml ]] && \
	cp /defaults/WebServer.xml /config/.airdc++/WebServer.xml

# permissions
chown -R abc:abc \
	/config

